{-# LANGUAGE BangPatterns, DataKinds, DeriveDataTypeable, FlexibleInstances, MultiParamTypeClasses #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
module Hadoop.Protos.RefreshCallQueueProtocolProtos (protoInfo, fileDescriptorProto) where
import Prelude ((+), (/))
import qualified Prelude as Prelude'
import qualified Data.Typeable as Prelude'
import qualified Data.Data as Prelude'
import qualified Text.ProtocolBuffers.Header as P'
import Text.DescriptorProtos.FileDescriptorProto (FileDescriptorProto)
import Text.ProtocolBuffers.Reflections (ProtoInfo)
import qualified Text.ProtocolBuffers.WireMessage as P' (wireGet,getFromBS)
 
protoInfo :: ProtoInfo
protoInfo
 = Prelude'.read
    "ProtoInfo {protoMod = ProtoName {protobufName = FIName \".hadoop.common\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [], baseName = MName \"RefreshCallQueueProtocolProtos\"}, protoFilePath = [\"Hadoop\",\"Protos\",\"RefreshCallQueueProtocolProtos.hs\"], protoSource = \"RefreshCallQueueProtocol.proto\", extensionKeys = fromList [], messages = [DescriptorInfo {descName = ProtoName {protobufName = FIName \".hadoop.common.RefreshCallQueueRequestProto\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [MName \"RefreshCallQueueProtocolProtos\"], baseName = MName \"RefreshCallQueueRequestProto\"}, descFilePath = [\"Hadoop\",\"Protos\",\"RefreshCallQueueProtocolProtos\",\"RefreshCallQueueRequestProto.hs\"], isGroup = False, fields = fromList [], descOneofs = fromList [], keys = fromList [], extRanges = [], knownKeys = fromList [], storeUnknown = False, lazyFields = False, makeLenses = False},DescriptorInfo {descName = ProtoName {protobufName = FIName \".hadoop.common.RefreshCallQueueResponseProto\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [MName \"RefreshCallQueueProtocolProtos\"], baseName = MName \"RefreshCallQueueResponseProto\"}, descFilePath = [\"Hadoop\",\"Protos\",\"RefreshCallQueueProtocolProtos\",\"RefreshCallQueueResponseProto.hs\"], isGroup = False, fields = fromList [], descOneofs = fromList [], keys = fromList [], extRanges = [], knownKeys = fromList [], storeUnknown = False, lazyFields = False, makeLenses = False}], enums = [], oneofs = [], services = [ServiceInfo {serviceName = ProtoName {protobufName = FIName \".hadoop.common.RefreshCallQueueProtocolService\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [MName \"RefreshCallQueueProtocolProtos\"], baseName = MName \"RefreshCallQueueProtocolService\"}, serviceMethods = [MethodInfo {methodName = ProtoName {protobufName = FIName \".hadoop.common.RefreshCallQueueProtocolService.refreshCallQueue\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [MName \"RefreshCallQueueProtocolProtos\",MName \"RefreshCallQueueProtocolService\"], baseName = MName \"RefreshCallQueue\"}, methodInput = ProtoName {protobufName = FIName \".hadoop.common.RefreshCallQueueRequestProto\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [MName \"RefreshCallQueueProtocolProtos\"], baseName = MName \"RefreshCallQueueRequestProto\"}, methodOutput = ProtoName {protobufName = FIName \".hadoop.common.RefreshCallQueueResponseProto\", haskellPrefix = [MName \"Hadoop\",MName \"Protos\"], parentModule = [MName \"RefreshCallQueueProtocolProtos\"], baseName = MName \"RefreshCallQueueResponseProto\"}}], serviceFilePath = [\"Hadoop\",\"Protos\",\"RefreshCallQueueProtocolProtos\",\"RefreshCallQueueProtocolService.hs\"]}], knownKeyMap = fromList []}"
 
fileDescriptorProto :: FileDescriptorProto
fileDescriptorProto
 = P'.getFromBS (P'.wireGet 11)
    (P'.pack
      "\197\a\n\RSRefreshCallQueueProtocol.proto\DC2\rhadoop.common\"\RS\n\FSRefreshCallQueueRequestProto\"\US\n\GSRefreshCallQueueResponseProto2\148\SOH\n\USRefreshCallQueueProtocolService\DC2q\n\DLErefreshCallQueue\DC2+.hadoop.common.RefreshCallQueueRequestProto\SUB,.hadoop.common.RefreshCallQueueResponseProto(\NUL0\NULBV\n\ESCorg.apache.hadoop.ipc.protoB\RSRefreshCallQueueProtocolProtosH\SOHP\NUL\128\SOH\NUL\136\SOH\SOH\144\SOH\NUL\160\SOH\SOH\184\SOH\NUL\216\SOH\NUL\248\SOH\NULJ\227\EOT\n\b\n\NUL\DC2\EOT\CAN\NUL3\SOH\n\b\n\SOH\b\DC2\ETX\CAN\NUL4\n\v\n\EOT\b\231\a\NUL\DC2\ETX\CAN\NUL4\n\f\n\ENQ\b\231\a\NUL\STX\DC2\ETX\CAN\a\DC3\n\r\n\ACK\b\231\a\NUL\STX\NUL\DC2\ETX\CAN\a\DC3\n\SO\n\a\b\231\a\NUL\STX\NUL\SOH\DC2\ETX\CAN\a\DC3\n\f\n\ENQ\b\231\a\NUL\a\DC2\ETX\CAN\SYN3\n\b\n\SOH\b\DC2\ETX\EM\NUL?\n\v\n\EOT\b\231\a\SOH\DC2\ETX\EM\NUL?\n\f\n\ENQ\b\231\a\SOH\STX\DC2\ETX\EM\a\ESC\n\r\n\ACK\b\231\a\SOH\STX\NUL\DC2\ETX\EM\a\ESC\n\SO\n\a\b\231\a\SOH\STX\NUL\SOH\DC2\ETX\EM\a\ESC\n\f\n\ENQ\b\231\a\SOH\a\DC2\ETX\EM\RS>\n\b\n\SOH\b\DC2\ETX\SUB\NUL$\n\v\n\EOT\b\231\a\STX\DC2\ETX\SUB\NUL$\n\f\n\ENQ\b\231\a\STX\STX\DC2\ETX\SUB\a\FS\n\r\n\ACK\b\231\a\STX\STX\NUL\DC2\ETX\SUB\a\FS\n\SO\n\a\b\231\a\STX\STX\NUL\SOH\DC2\ETX\SUB\a\FS\n\f\n\ENQ\b\231\a\STX\ETX\DC2\ETX\SUB\US#\n\b\n\SOH\b\DC2\ETX\ESC\NUL,\n\v\n\EOT\b\231\a\ETX\DC2\ETX\ESC\NUL,\n\f\n\ENQ\b\231\a\ETX\STX\DC2\ETX\ESC\a$\n\r\n\ACK\b\231\a\ETX\STX\NUL\DC2\ETX\ESC\a$\n\SO\n\a\b\231\a\ETX\STX\NUL\SOH\DC2\ETX\ESC\a$\n\f\n\ENQ\b\231\a\ETX\ETX\DC2\ETX\ESC'+\n\b\n\SOH\STX\DC2\ETX\FS\b\NAK\n+\n\STX\EOT\NUL\DC2\EOT!\NUL\"\SOH\SUB\US*\n  Refresh callqueue request.\n\n\n\n\ETX\EOT\NUL\SOH\DC2\ETX!\b$\n\RS\n\STX\EOT\SOH\DC2\EOT'\NUL(\SOH\SUB\DC2*\n void response.\n\n\n\n\ETX\EOT\SOH\SOH\DC2\ETX'\b%\n@\n\STX\ACK\NUL\DC2\EOT-\NUL3\SOH\SUB4*\n Protocol which is used to refresh the callqueue.\n\n\n\n\ETX\ACK\NUL\SOH\DC2\ETX-\b'\n(\n\EOT\ACK\NUL\STX\NUL\DC2\EOT1\STX2-\SUB\SUB*\n Refresh the callqueue.\n\n\f\n\ENQ\ACK\NUL\STX\NUL\SOH\DC2\ETX1\ACK\SYN\n\f\n\ENQ\ACK\NUL\STX\NUL\STX\DC2\ETX1\ETB3\n\f\n\ENQ\ACK\NUL\STX\NUL\ETX\DC2\ETX2\SO+")